### PR TITLE
add atom:// hyperlinks

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change

Recognize `atom://` uris as valid hyperlinks

### Benefits

`atom://` uris will be recognized as hyperlinks

### CODE REVIEW

**Comment by UziTech** [comment]
@atom any feedback?

**Comment by 50Wliu** [comment]
This doesn't seem too useful without atom/atom#16940.  Will merge if/when that PR is merged.

**Comment by UziTech** [comment]
@50Wliu atom/atom#16940 only applies to markdown preview and other places that atom has clickable links.

This PR makes `atom://` links in a text editor have the correct scope. They don't really have anything to do with each other.

Clicking on an `atom://` link inside of atom to open a file is already possible with [hyperlink-hyperclick](https://atom.io/packages/hyperlink-hyperclick)

**Comment by UziTech** [comment]
`link` [uses shell.openExternal](https://github.com/atom/link/blob/add8170e69c84e1ea438e22b6a023a32f6582eaf/lib/link.js#L28) to open links, so it too won't be affected by atom/atom#16940 (or this PR for that matter since it explicitly only opens `http(s)://` links)

**Comment by UziTech** [comment]
atom/atom#16940 was merged so this should be good to merge as well as atom/link#33

**Pull request merged**
