### PR TITLE
prevent multiple `#` from matching as valid url

### PR DESCRIPTION
**Pull request by tollus**
This prevents URLs from being matched when they have multiple pounds in the URL. 

For example, this link should not be matched:
CFML: `setBaseURL("http://#cgi.HTTP_HOST#/#getSetting('AppMapping')#/");`

I reverted to old regex from 0c9bbc7, and added a negative lookahead to prevent multiple pound symbols in a URL. To prevent from throwing off cfml syntax.

Reference for previous PR: #5

Also reference to the issue from atuttle/atom-language-cfml#60

The main question I have is should it match the first part of the URL up until the first `#` if there are multiple.

won't match:
- http://github.com/#username#
- http://#domain#/#username#

will match
- http://github.com/atom/#start-of-content
- http://github.com/atom/

### CODE REVIEW

**Comment by elpete** [comment]
I think this is acceptable for the CFML world. URLs with CFML in it would not be able to be actually linked like normal URL's. 

A better solution would be like what happens with PHP or CoffeeScript interpolation, where the entire string is marked as a URL, but the interpolated part is still marked correctly. This seems to be difficult since `#` can be part of the URL string.

**Comment by elpete** [comment]
@nathansobo Sorry for the ping, but I wanted to check if there was anything else you needed from us on this pull request.  I would help clear up a few issues in the CFML land.

**Comment by kevinsawicki** [comment]
This pull request now have a conflict, would you mind updating it and resolving them? Thanks.

**Comment by tollus** [comment]
I've updated the conflicts. I copied over the current regex instead of the revert like I mentioned in the open comment.

**Comment by UziTech** [comment]
This PR can be closed

fixed in 1957a066d91fd6fae8756a2f1909797a439695ea

**Comment by rsese** [comment]
Thanks @UziTech :bow:

**Pull request closed without merging**
